import { ContextWrapper } from "@/context";
import "./globals.css";
import AppContainer from "@/components/AppContainer";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "React Context API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <AppContainer>
          <ContextWrapper>{children}</ContextWrapper>
        </AppContainer>
      </body>
    </html>
  );
}
